import { LegalFlag, Severity } from './types';

function getSeverityWeight(severity: Severity): number {
  switch (severity) {
    case 'Critical': return 4;
    case 'High': return 3;
    case 'Medium': return 2;
    case 'Low': return 1;
    default: return 0;
  }
}

function sortFlags(flags: LegalFlag[]): LegalFlag[] {
  return [...flags].sort((a, b) => getSeverityWeight(b.severity) - getSeverityWeight(a.severity));
}

export function generateMarkdownReport(flags: LegalFlag[], pageUrl: string, pageTitle: string): string {
  const sorted = sortFlags(flags);
  const now = new Date().toLocaleString();

  const lines = [
    '# TermCheck Analysis Report',
    '',
    `**Page:** [${pageTitle}](${pageUrl})`,
    `**Date:** ${now}`,
    `**Total Flags:** ${flags.length}`,
    '',
    '## Severity Summary',
    '',
    `- Critical: ${sorted.filter(f => f.severity === 'Critical').length}`,
    `- High: ${sorted.filter(f => f.severity === 'High').length}`,
    `- Medium: ${sorted.filter(f => f.severity === 'Medium').length}`,
    `- Low: ${sorted.filter(f => f.severity === 'Low').length}`,
    '',
    '## Findings',
    '',
  ];

  if (sorted.length === 0) {
    lines.push('No significant red flags identified.', '');
  } else {
    sorted.forEach((flag, idx) => {
      lines.push(`### ${idx + 1}. ${flag.category} (${flag.severity})`, '');
      lines.push(`**Summary:** ${flag.summary}`, '');
      lines.push(`**Quote:**`, '');
      lines.push(`> ${flag.quote}`, '');
      lines.push('');
    });
  }

  lines.push(
    '---',
    '',
    '*Generated by TermCheck - AI Legal Assistant*',
    '*This report is for informational purposes only and does not constitute legal advice.*'
  );

  return lines.join('\n');
}

export function generateJSONReport(flags: LegalFlag[], pageUrl: string, pageTitle: string): string {
  const report = {
    generatedAt: new Date().toISOString(),
    pageUrl,
    pageTitle,
    summary: {
      total: flags.length,
      critical: flags.filter((f) => f.severity === 'Critical').length,
      high: flags.filter((f) => f.severity === 'High').length,
      medium: flags.filter((f) => f.severity === 'Medium').length,
      low: flags.filter((f) => f.severity === 'Low').length,
    },
    flags: sortFlags(flags).map((f) => ({
      category: f.category,
      severity: f.severity,
      summary: f.summary,
      quote: f.quote,
    })),
  };
  return JSON.stringify(report, null, 2);
}

export function downloadReport(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadMarkdownReport(flags: LegalFlag[], pageUrl: string, pageTitle: string): void {
  const content = generateMarkdownReport(flags, pageUrl, pageTitle);
  const safeTitle = pageTitle.replace(/[^a-z0-9]/gi, '_').substring(0, 50);
  downloadReport(content, `termcheck-report-${safeTitle}.md`, 'text/markdown');
}

export function downloadJSONReport(flags: LegalFlag[], pageUrl: string, pageTitle: string): void {
  const content = generateJSONReport(flags, pageUrl, pageTitle);
  const safeTitle = pageTitle.replace(/[^a-z0-9]/gi, '_').substring(0, 50);
  downloadReport(content, `termcheck-report-${safeTitle}.json`, 'application/json');
}
